version: "3"
services:
  web:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
        
  redis:
    image: "redis:alpine"
  
  watchtower:
    image:  containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock