version: '3'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    env_file:
      - .env
  
  mongo-express:
    image: mongo-express
    ports:
      - 8080:8081
    env_file:
      - .env

